# python main_test_clustertransformer.py --benchmark Set5 --task swin_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_54/250000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task noswin_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_56/250000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task onlySA_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_200/250000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task onlySA_shallow_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_299/250000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task onlySA_thin_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_267/250000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task onlySA_short_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_319/250000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task onlySA_tooshallow_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_296/235000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task onlySA_toothin_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_295/250000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task onlySA_tooshort_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_293/250000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task kmeans_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_264/95000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task kmeans_post_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_297/250000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task kmeans_last_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_298/250000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task kmeans_postkeepv_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_288/465000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task kmeans_postkeepvnorecycle_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_290/500000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task onlySA_shallow_no_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_335/250000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task onlySA_thin_no_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_302/250000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task onlySA_short_no_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_352/250000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task onlySA_tooshallow_no_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_348/250000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task onlySA_toothin_no_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_337/250000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task onlySA_tooshort_no_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_336/250000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task blockcluster_noswin_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_330/250000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task random_noswin_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_334/250000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task randomfix_noswin_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_339/250000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task intrakmeans_post_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_346/195000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task kmeans_normpost_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_385/250000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task halfkmeans_post_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_390/250000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task kmeans_postkeepv_bias_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_397/230000/model/G.pth
# python main_test_clustertransformer.py --benchmark Set5 --task kmeans_tooshort_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_404/245000/model/G.pth
python main_test_clustertransformer.py --benchmark Set5 --task kmeans_tooshortkeepv_sr --model_path nsmltrained_models/KR80934_CVLAB_SR_406/190000/model/G.pth